# Generated by Django 3.0.3 on 2020-03-29 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_id', models.CharField(max_length=255)),
                ('vin', models.CharField(max_length=17)),
                ('make', models.CharField(max_length=255)),
                ('model', models.CharField(blank=True, max_length=255, null=True)),
                ('trim', models.CharField(blank=True, max_length=255, null=True)),
                ('body_style', models.CharField(blank=True, max_length=255, null=True)),
                ('mileage', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('first_date', models.DateField()),
                ('last_date', models.DateField()),
                ('duration', models.IntegerField()),
                ('seller_id', models.IntegerField()),
            ],
            options={
                'unique_together': {('listing_id', 'vin')},
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=31, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('address', models.TextField()),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
            ],
            options={
                'unique_together': {('phone_number', 'name')},
            },
        ),
    ]
