# Generated by Django 3.0.3 on 2020-04-14 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pscraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='address',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='phone_number',
            field=models.CharField(max_length=31),
        ),
    ]
