# Generated by Django 3.0.3 on 2020-05-01 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pscraper', '0002_auto_20200413_1801'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'verbose_name': 'Dynamic Data', 'verbose_name_plural': 'Dynamic Data'},
        ),
    ]
