# Generated by Django 3.0.3 on 2020-03-20 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pscraper', '0002_auto_20200319_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='body_style',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='trim',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
