# Generated by Django 3.0.3 on 2020-05-09 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pscraper', '0003_auto_20200430_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='mileage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
