# Generated by Django 3.0.3 on 2020-06-28 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pscraper', '0004_history_mileage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vehicle',
            new_name='CarsComVehicle',
        ),
        migrations.AddField(
            model_name='history',
            name='marketplace',
            field=models.CharField(default='Cars.com', max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='AutoTraderVehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=17, unique=True)),
                ('listing_id', models.CharField(max_length=255)),
                ('make', models.CharField(max_length=255)),
                ('model', models.CharField(blank=True, max_length=255, null=True)),
                ('trim', models.CharField(blank=True, max_length=255, null=True)),
                ('body_style', models.CharField(blank=True, max_length=255, null=True)),
                ('mileage', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('first_date', models.DateField()),
                ('last_date', models.DateField()),
                ('duration', models.IntegerField()),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pscraper.Seller')),
            ],
        ),
    ]
