# Generated by Django 3.0.3 on 2020-06-30 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pscraper', '0005_auto_20200628_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='phone_number',
            field=models.CharField(blank=True, max_length=31, null=True),
        ),
    ]
